stages:
- build
- test

nginx:build:
  stage: build
  image: docker
  services:
  - docker:dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
  script:
  - cd nginx
  - docker build . -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
                   -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

nginx:test:
  stage: test
  needs: ["nginx:build"]
  image: docker
  services:
  - docker:dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
  script:
  - docker run -d --name test $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  - export OUTPUT=$(docker exec test curl -sSfL localhost)
  - test "$OUTPUT" == "It works!" || (echo $OUTPUT && exit 1)
