stages:
- build
- test
- deploy

default:
  services: 
  - docker:dind
variables:
  DOCKER_HOST: "tcp://docker:2375"

nginx:build:
  stage: build
  image: docker
  script:
  - cd nginx
  - docker build . -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

nginx:test:
  stage: test
  needs: 
  - nginx:build
  image: docker
  script:
  - docker run -d --name test $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  - export OUTPUT=$(docker exec test curl -sSfL localhost)
  - test "$OUTPUT" == "It works!" || (echo $OUTPUT && exit 1)

nginx:deploy:
  stage: deploy
  needs:
  - nginx:test
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base
  script:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - aws eks update-kubeconfig --name $CLUSTER_NAME
  - sed -i "s/_IMAGE_/$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA/g" nginx/kubernetes/deploy.yaml
  - kubectl apply -f nginx/kubernetes/deploy.yaml
