stages:
- build

build app:
  stage: build
  image: docker
  services:
  - docker:dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
  script:
  - cd nginx
  - docker build . -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
                   -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
